export const ErrorCodes = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  PARSE_ERROR: 'PARSE_ERROR',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  AUTH_MISSING_HEADER: 'AUTH_MISSING_HEADER',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
  AUTH_SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  PLANNER_UNAVAILABLE: 'PLANNER_UNAVAILABLE',
  DUPLICATE_TECHNIQUE: 'DUPLICATE_TECHNIQUE',
  INVALID_TECHNIQUE_ID: 'INVALID_TECHNIQUE_ID',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_CANCELLED: 'AUTH_CANCELLED',
  AUTH_FAILED: 'AUTH_FAILED',
  SYNC_FAILED: 'SYNC_FAILED',
  BROWSER_UNAVAILABLE: 'BROWSER_UNAVAILABLE',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ApiErrorBody = {
  error?: string;
  code?: string;
  field?: string;
  requestId?: string;
};
